VERSION=0.1

CHICORY_VERSION=1.7.5
MSGPACK_VERSION=0.9.12
JAVAPARSER_VERSION=3.27.1
OBJECTWEB_VERSION=9.9
JUNIT_VERSION=6.1.0
OPENTEST4J_VERSION=1.3.0
APIGUARDIAN_VERSION=1.1.2
LIBS=libs

# Needed to run the application
CLASSPATH=.
CLASSPATH=${LIBS}/log-${CHICORY_VERSION}.jar:${CLASSPATH}
CLASSPATH=${LIBS}/runtime-${CHICORY_VERSION}.jar:${CLASSPATH}
CLASSPATH=${LIBS}/wasi-${CHICORY_VERSION}.jar:${CLASSPATH}
CLASSPATH=${LIBS}/wasm-${CHICORY_VERSION}.jar:${CLASSPATH}
CLASSPATH=${LIBS}/msgpack-core-${MSGPACK_VERSION}.jar:${CLASSPATH}

# Needed to build the application
CLASSPATH_BUILD=${CLASSPATH}
CLASSPATH_BUILD=${LIBS}/build-time-compiler-${CHICORY_VERSION}.jar:${CLASSPATH_BUILD}
CLASSPATH_BUILD=${LIBS}/compiler-${CHICORY_VERSION}.jar:${CLASSPATH_BUILD}
CLASSPATH_BUILD=${LIBS}/javaparser-core-${JAVAPARSER_VERSION}.jar:${CLASSPATH_BUILD}
CLASSPATH_BUILD=${LIBS}/asm-commons-${OBJECTWEB_VERSION}.jar:${CLASSPATH_BUILD}
CLASSPATH_BUILD=${LIBS}/asm-${OBJECTWEB_VERSION}.jar:${CLASSPATH_BUILD}
CLASSPATH_BUILD=${LIBS}/chicory-library-generator.jar:${CLASSPATH_BUILD}

# Needed to build and run the tests
CLASSPATH_TEST=${CLASSPATH}
CLASSPATH_TEST=${LIBS}/junit-jupiter-api-${JUNIT_VERSION}.jar:${CLASSPATH_TEST}
CLASSPATH_TEST=${LIBS}/junit-platform-commons-${JUNIT_VERSION}.jar:${CLASSPATH_TEST}
CLASSPATH_TEST=${LIBS}/opentest4j-${OPENTEST4J_VERSION}.jar:${CLASSPATH_TEST}
CLASSPATH_TEST=${LIBS}/apiguardian-api-${APIGUARDIAN_VERSION}.jar:${CLASSPATH_TEST}

WASM_FILE=target/rust/wasm32-wasip1/debug/wasm_lib.wasm
WASM_OPTIMIZED_FILE=target/rust/wasm32-wasip1/release/wasm_lib.wasm
WASM_TARGET_RESOURCES=target/generated-resources/chicory-compiler
WASM_TARGET_SOURCES=target/generated-sources/chicory-compiler

JAR_FILE=target/quickjs-${VERSION}.jar
TEST_JAR_FILE=target/quickjs-test-${VERSION}.jar
